### ISSUE TITLE
How to use this module to show data on browser?

### ISSUE THREAD

**Issue by asmitarane** [hook42/examples#1]
I want to show data on browser.

Please help me out for this.

**Comment by asmitarane** [comment]
I am asking about below module 

https://github.com/hook42/examples/tree/master/d8

**Comment by daggerhart** [comment]
Hi @asmitarane,

You can enable this module on your Drupal 8 website. When the module is enabled it will provide a new Block named "Cat Facts" that you can place on the page.

See this link for more details on installing and using Drupal 8 modules: https://www.drupal.org/docs/8/extending-drupal-8/installing-drupal-8-modules
